### PR TITLE
Fix structure_load/2 for MySQL 9.4+

### LINKED ISSUE #684: mysql-client@9.4 fails to run ecto.load
### Elixir version

Elixir 1.16.3 (compiled with Erlang/OTP 26)

### Database and Version

mysql:8

### Ecto Versions

* ecto 3.12.5 * ecto_sql 3.12.1

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.7.1

### Current behavior

When we run `mix ecto.setup`

```elixir
[
 "ecto.setup": [
        "ecto.drop -r MyRepo",
        "ecto.create -r MyRepo",
        "ecto.load -d mysql-dump/dump.sql -r MyRepo --skip-if-loaded"
  ]
]
```

The `ecto.load` fails:

```
* (Mix) The structure for MyRepo couldn't be loaded: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOURCE mysql-dump/dump.sql' at line 1
```

We isolated the issue, `brew install mysql-client@9.4.0` fails, but works for `brew install mysql-client@9.3.0` (we can not longer install 9.3.0 using brew btw, this is just to showcase the situation.

So something changed in the `mysql` CLI that is causing the breakage.

### Expected behavior

It works with `brew install mysql-client@9.4.0`

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #684.

On MySQL 9.4+, `--execute "SOURCE {path}"` is no longer supported.

### CODE REVIEW

File: lib/ecto/adapters/myxql.ex [hunk 1]
```diff
@@ -416,16 +416,18 @@ defmodule Ecto.Adapters.MyXQL do
...
-      "--execute",
-      "SET FOREIGN_KEY_CHECKS = 0; SOURCE #{path}; SET FOREIGN_KEY_CHECKS = 1",
-      "--database",
-      config[:database]
-    ]
-
-    case run_with_cmd("mysql", config, args) do
-      {_output, 0} -> {:ok, path}
-      {output, _} -> {:error, output}
+    with {:ok, contents} <- File.read(path) do
```
Comment (josevalim) [inline lib/ecto/adapters/myxql.ex:419]: Will downstream be able to handle {:error, atom()}?

**Review by yordis — APPROVED** [review]
I ran the test locally, with `mysql-client@9.4` and it is passing now.

Thank y'all!
